### ISSUE TITLE
阅读代码的时候发现个小疑问

### ISSUE THREAD

**Issue by NumberFive** [msching/MCSimpleAudioPlayer#5]
非常感谢你的iOS音频播放系列文章，阅读你的代码的时候发现个小疑问
在MCAudioFile.m的第119行的for循环：
`for (int i = 0; i * sizeof(AudioFormatListItem) < formatListSize; i += sizeof(AudioFormatListItem))`
是不是应该为：
`for (int i = 0; i * sizeof(AudioFormatListItem) < formatListSize; i++)`
或者：
`for (int i=0; i < formatListSize; i += sizeof(AudioFormatListItem)`

**Comment by msching** [comment]
对，应该是i++
